
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRMS.Core.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public long Id { get; set; }

    public long UserTypeId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string WorkPhone { get; set; }

    public string UserName { get; set; }

    public string SaltKey { get; set; }

    public string PasswordHash { get; set; }

    public Nullable<bool> DefaultPassword { get; set; }

    public Nullable<System.DateTime> LastLoginDate { get; set; }

    public Nullable<bool> IsOnLine { get; set; }

    public Nullable<int> AccountStatus { get; set; }

    public Nullable<long> ReportingTo { get; set; }

    public Nullable<long> CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public Nullable<long> ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public Nullable<long> AssignedRegionId { get; set; }

    public string CountryCode { get; set; }



    public virtual UserDetail UserDetail { get; set; }

    public virtual UserType UserType { get; set; }

}

}
