USE [master]
GO
/****** Object:  Database [TrialDB]    Script Date: 01/30/2019 7:34:54 PM ******/
CREATE DATABASE [TrialDB]
 
GO
ALTER DATABASE [TrialDB] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TrialDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TrialDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TrialDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TrialDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TrialDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TrialDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [TrialDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TrialDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TrialDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TrialDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TrialDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TrialDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TrialDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TrialDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TrialDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TrialDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TrialDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TrialDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TrialDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TrialDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TrialDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TrialDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TrialDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TrialDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TrialDB] SET  MULTI_USER 
GO
ALTER DATABASE [TrialDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TrialDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TrialDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TrialDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TrialDB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [TrialDB]
GO
/****** Object:  Table [dbo].[Course]    Script Date: 01/30/2019 7:34:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Course](
	[CourseID] [int] IDENTITY(1,1) NOT NULL,
	[CourseName] [nvarchar](50) NOT NULL,
	[CourseDescription] [nvarchar](100) NULL,
 CONSTRAINT [PK_Course] PRIMARY KEY CLUSTERED 
(
	[CourseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [TrialDB] SET  READ_WRITE 
GO
